[tool.ruff]
select = [
    "A",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    "D",
    "DTZ",
    "E",
    "ERA",
    "EXE",
    "F",
    "FA",
    "FLY",
    "G",
    "I",
    "INP",
    "INT",
    "ISC",
    "N",
    "PERF",
    "PIE",
    "PT",
    "PTH",
    "PYI",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLOT",
    "T100",
    "T20",
    "TRY",
    "UP",
    "W",
    "YTT",
]
target-version = "py312"
